name: owner_app
description: SEAVAIG Owner Executive CRM Flutter Mobile Application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  url_launcher: ^6.2.1
  supabase_flutter: ^2.17.2
  shared_preferences: ^2.5.5
  image_picker: ^1.2.3
  pdf: ^3.13.0
  printing: ^5.15.0
  fl_chart: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
